### ISSUE TITLE
SuccessStory - No Steam configuration & SuccessStory - Bad Steam configuration

### ISSUE THREAD

**Issue by trillex** [Lacro59/playnite-successstory-plugin#105]
After a completely fresh installation of SuccessStory, I am having issues receiving Steam achievements. 

I get the following in the log before and after toggling API use: 

```
17-02 20:23:11.881|ERROR|Common:SuccessStory [H:\GitHub\Lacro59\playnite-successstory-plugin\Views\SuccessStorySettingsView.xaml.cs 424] - Error on RefreshData(Steam, False) for Majesty 2
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at SuccessStory.Clients.SteamAchievements.CheckIsPublic(Int32 AppId) in H:\GitHub\Lacro59\playnite-successstory-plugin\Clients\SteamAchievements.cs:line 222
   at SuccessStory.Views.SuccessStorySettingsView.<>c__DisplayClass45_0.<RefreshData>b__0() in H:\GitHub\Lacro59\playnite-successstory-plugin\Views\SuccessStorySettingsView.xaml.cs:line 424
17-02 20:23:11.881|ERROR|GenericAchievements:SuccessStory - No Steam configuration
17-02 20:23:11.881|ERROR|Common:SuccessStory [H:\GitHub\Lacro59\playnite-successstory-plugin\Views\SuccessStorySettingsView.xaml.cs 424] - Error on RefreshData(Steam, False) for Blood Bowl: Death Zone
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at SuccessStory.Clients.SteamAchievements.CheckIsPublic(Int32 AppId) in H:\GitHub\Lacro59\playnite-successstory-plugin\Clients\SteamAchievements.cs:line 222
   at SuccessStory.Views.SuccessStorySettingsView.<>c__DisplayClass45_0.<RefreshData>b__0() in H:\GitHub\Lacro59\playnite-successstory-plugin\Views\SuccessStorySettingsView.xaml.cs:line 424
17-02 20:23:35.040|ERROR|GenericAchievements:SuccessStory - No Steam configuration
17-02 20:23:37.403|INFO|SuccessStorySettingsView:IsCancellationRequested for RefreshData(Steam, True)
17-02 20:23:41.546|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChild [PART_ButtonMoreActions] not find
17-02 20:23:41.546|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedInfoBarFS [PART_ButtonContext] not find
17-02 20:23:41.546|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChildFS [PART_ButtonContext] not find
17-02 20:23:41.546|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.PluginSettingsWindowFactory, True.
17-02 20:30:41.618|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.SettingsWindowFactory
17-02 20:30:50.219|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChild [PART_ButtonMoreActions] not find
17-02 20:30:50.219|WARN|PlayniteUiHelper:CommonPluginsShared - RemoveSpInfoBarFS() without SpInfoBarFSName
17-02 20:30:50.219|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChildFS [PART_ButtonContext] not find
17-02 20:30:50.226|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChild [PART_ButtonMoreActions] not find
17-02 20:30:50.226|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedInfoBarFS [PART_ButtonContext] not find
17-02 20:30:50.226|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChildFS [PART_ButtonContext] not find
17-02 20:30:50.226|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.SettingsWindowFactory, True.
17-02 20:30:50.246|WARN|PlayniteUiHelper:ScreenshotsVisualizer - No data for Grand Theft Auto V
17-02 20:30:56.024|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.SettingsWindowFactory
17-02 20:31:04.801|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChild [PART_ButtonMoreActions] not find
17-02 20:31:04.805|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedInfoBarFS [PART_ButtonContext] not find
17-02 20:31:04.805|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChildFS [PART_ButtonContext] not find
17-02 20:31:04.805|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChild [PART_ButtonMoreActions] not find
17-02 20:31:04.805|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedInfoBarFS [PART_ButtonContext] not find
17-02 20:31:04.805|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChildFS [PART_ButtonContext] not find
17-02 20:31:04.805|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.SettingsWindowFactory, True.
17-02 20:31:07.233|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.SettingsWindowFactory
17-02 20:31:17.502|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChild [PART_ButtonMoreActions] not find
17-02 20:31:17.502|WARN|PlayniteUiHelper:CommonPluginsShared - RemoveSpInfoBarFS() without SpInfoBarFSName
17-02 20:31:17.502|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChildFS [PART_ButtonContext] not find
17-02 20:31:17.508|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChild [PART_ButtonMoreActions] not find
17-02 20:31:17.508|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedInfoBarFS [PART_ButtonContext] not find
17-02 20:31:17.508|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChildFS [PART_ButtonContext] not find
17-02 20:31:17.508|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.SettingsWindowFactory, True.
17-02 20:31:17.527|WARN|PlayniteUiHelper:ScreenshotsVisualizer - No data for Grand Theft Auto V
17-02 20:31:18.784|WARN|PlayniteUiHelper:GameActivity - No data for BioShock
17-02 20:31:18.784|WARN|PlayniteUiHelper:ScreenshotsVisualizer - No data for BioShock
17-02 20:31:23.259|ERROR|GenericAchievements:SuccessStory - No Steam configuration
17-02 20:31:23.259|WARN|PluginDatabaseObject3:SuccessStory - Bad Steam configuration
17-02 20:31:31.700|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.SettingsWindowFactory
17-02 20:31:41.724|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChild [PART_ButtonMoreActions] not find
17-02 20:31:41.724|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedInfoBarFS [PART_ButtonContext] not find
17-02 20:31:41.724|ERROR|IntegrationUI:CommonPluginsShared - btGameSelectedActionBarChildFS [PART_ButtonContext] not find
17-02 20:31:41.724|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.SettingsWindowFactory, True.
17-02 20:31:49.587|ERROR|GenericAchievements:SuccessStory - No Steam configuration
17-02 20:31:49.587|WARN|PluginDatabaseObject3:SuccessStory - Bad Steam configuration
```

My Steam profile is completely open (steamcommunity.com/id/trillex) and my Steam is properly authenticated inside Playnite

![image](https://user-images.githubusercontent.com/6444691/108258125-020ae680-7160-11eb-8886-f17694fad43b.png)

I believe that this is different from #97 so opening a new ticket, just to be safe.

**Comment by darklinkpower** [comment]
You need to use an API Key. Check https://github.com/Lacro59/playnite-successstory-plugin/wiki/Configure-Steam

**Comment by trillex** [comment]
That's on me. 

I must have read it as needing the profile to be either public OR have the API key. Not both.
