### ISSUE TITLE
Importing from Steam not working: Steam profile is not public.

### ISSUE THREAD

**Issue by t0mtee** [Lacro59/playnite-successstory-plugin#127]
```
20-07 18:08:03.014|WARN|GenericAchievements:SuccessStory - Steam profil is private
20-07 18:08:03.014|ERROR|Common:SuccessStory [D:\GitHub\Playnite\Lacro59\playnite-successstory-plugin\Clients\SteamAchievements.cs 418] - Error on GetPlayerAchievements(76561198845713892, 524220, english)
System.Net.WebException: The remote server returned an error: (403) Forbidden.

Server stack trace: 
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at SteamKit2.WebAPI.AsyncInterface.<>c__DisplayClass6_0.<Call>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Exception rethrown at [0]: 
   at SteamKit2.WebAPI.Interface.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , String , Int32 , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at SuccessStory.Clients.SteamAchievements.GetPlayerAchievements(Int32 AppId) in D:\GitHub\Playnite\Lacro59\playnite-successstory-plugin\Clients\SteamAchievements.cs:line 418
```
My Steam profile is private, but I have an API key put in.

**Comment by Lacro59** [comment]
Have you try with the beta version in Playnite9?

**Comment by OsoaGitHub** [comment]
> 
> 
> Have you try with the beta version in Playnite9?

I have not since some of my plugins are not compatible yet

**Comment by Lacro59** [comment]
Can you try this?
https://github.com/Lacro59/playnite-successstory-plugin/issues/479#issuecomment-2191342743
