### ISSUE TITLE
 Failed to parse.System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by shakeyourbunny** [Lacro59/playnite-successstory-plugin#15]
There seem to be some gotchas in downloading the achievement data:

>2020-06-15 23:12:11.9193|DEBUG:Downloading string content from https://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v0001/?appid=450220&key=xxxx&steamid=yyyy using System.Text.UTF8Encoding encoding.
>2020-06-15 23:12:12.3163|ERROR:SuccessStory [107] - Failed to parse.System.NullReferenceException: Object reference not set to an instance of an object.
   at SuccessStory.Clients.SteamAchievements.GetAchievements(IPlayniteAPI PlayniteApi, Guid Id, String PluginUserDataPath) in J:\Lacro59\playnite-successstory-plugin\Clients\SteamAchievements.cs:line 107

Link to error'd line: https://github.com/Lacro59/playnite-successstory-plugin/blob/815312100da8f03be971664c631a6f359a96dc74/Clients/SteamAchievements.cs#L107

I guess you should double-check the retrieved result from the API call not only if it is not "", but also not NULL. An empty string ("") is something else than NULL, so parsing the latter with "JObject resultObj = JObject.Parse(ResultWeb);" creates this error.

Affected Steam AppIDs which produce these error message:
450220: https://steamdb.info/app/450220/ -- Overload: Playable Teaser
257260: https://steamdb.info/app/257260/ -- Inherit the Earth: Quest for the Orb
822830: https://steamdb.info/app/822830/ -- Ouroboros
485340: https://steamdb.info/app/485340/ -- The Orchard of Stray Sheep
346610: https://steamdb.info/app/346610/ -- Racecraft
328760: SanctuaryRPG: Black Edition
302010: The Blue Flamingo
219740: Don't Starve
230170: Divinity: Dragon Commander Beta
434520: Simutrans
700590: Ghostly Horizon
632360: Risk of Rain 2
734580: BattleRush

Dunno why these cause issues, but after downloading the achievements, the success story diagram windows does not open, but only that something could not be rendered because of null exception.

My guess is that either the statistics window expects some data structure which is not present after producing the error mentioned above and/or there is no proper fallback if one or more achievement pictures are not downloadable. In the latter case, the statistics plugin should use a default symbol as a fallback.

**Comment by shakeyourbunny** [comment]
>2020-06-16 21:11:00.2929|ERROR:Failed to execute extension function.System.IO.FileFormatException: The image decoder cannot decode the image. The image might be corrupted. ---> System.Runtime.InteropServices.COMException: The image is unrecognized. (Exception from HRESULT: 0x88982F60)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at SuccessStory.SuccessView.GetListGame(String SearchGameName) in J:\Lacro59\playnite-successstory-plugin\Views\SuccessStoryView.xaml.cs:line 128
   at SuccessStory.SuccessView..ctor(SuccessStorySettings settings, IPlayniteAPI PlayniteApi, String PluginUserDataPath) in J:\Lacro59\playnite-successstory-plugin\Views\SuccessStoryView.xaml.cs:line 66
   at SuccessStory.SuccessStory.<GetFunctions>b__9_0() in J:\Lacro59\playnite-successstory-plugin\SuccessStory.cs:line 60
   at Playnite.SDK.ExtensionFunction.Invoke()
   at Playnite.Plugins.ExtensionFactory.InvokeExtension(ExtensionFunction function, Exception& error) in E:\Devel\Playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 415
>2020-06-16 21:11:09.6227|DEBUG:Invoking extension function Success Story
>2020-06-16 21:11:09.6227|INFO:SuccessStory - SuccessStoryView
>2020-06-16 21:11:10.8459|ERROR:Failed to execute extension >function.System.IO.FileFormatException: The image decoder cannot decode the image. The image might be corrupted. ---> System.Runtime.InteropServices.COMException: The image is unrecognized. (Exception from HRESULT: 0x88982F60)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at SuccessStory.SuccessView.GetListGame(String SearchGameName) in J:\Lacro59\playnite-successstory-plugin\Views\SuccessStoryView.xaml.cs:line 128
   at SuccessStory.SuccessView..ctor(SuccessStorySettings settings, IPlayniteAPI PlayniteApi, String PluginUserDataPath) in J:\Lacro59\playnite-successstory-plugin\Views\SuccessStoryView.xaml.cs:line 66
   at SuccessStory.SuccessStory.<GetFunctions>b__9_0() in J:\Lacro59\playnite-successstory-plugin\SuccessStory.cs:line 60
   at Playnite.SDK.ExtensionFunction.Invoke()
   at Playnite.Plugins.ExtensionFactory.InvokeExtension(ExtensionFunction function, Exception& error) in E:\Devel\Playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 415

**Comment by shakeyourbunny** [comment]
This is the current buggy extension data for debugging purposes.

I could not attach it directly, it seems that something is unpacking, doing an antivirus scan and choking on the about 7000 files in it... so I uploaded it on an one-click hoster.

success story extension data.zip: https://uptobox.com/yxh78rqj0qhl

**Comment by Funsponge** [comment]
Having this issue particularly when trying pull Epic achievements.

[SuccessStory_2024-12-15.zip](https://github.com/user-attachments/files/18138769/SuccessStory_2024-12-15.zip)
