### ISSUE TITLE
When starting playnite having an error

### ISSUE THREAD

**Issue by Jhanlon95** [Lacro59/playnite-successstory-plugin#234]
I'm on the latest version 2.6.2. When starting playnite I am seeing an error appearing in my notifications when I click on it it's creating a log output file which I have attached. [SuccessStory_2021-12-03.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/7649746/SuccessStory_2021-12-03.zip)

When checking the extension.log I am seeing this error:

03-12 12:55:54.404|ERROR|SuccessStory#Common:Error on OnGameSelected()|D:\GitHub\Lacro59\playnite-successstory-plugin\source\SuccessStory.cs|0
System.NullReferenceException: Object reference not set to an instance of an object.
   at CommonPluginsShared.Collections.PluginDatabaseObject`3.GetOnlyCache(Guid Id) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\Collections\PluginDatabaseObject.cs:line 551
   at SuccessStory.Services.SuccessStoryDatabase.Get(Guid Id, Boolean OnlyCache, Boolean Force) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 130
   at CommonPluginsShared.Collections.PluginDatabaseObject`3.Get(Game game, Boolean OnlyCache, Boolean Force) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\Collections\PluginDatabaseObject.cs:line 569
   at SuccessStory.Services.SuccessStoryDatabase.SetThemesResources(Game game) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 911
   at SuccessStory.SuccessStory.OnGameSelected(OnGameSelectedEventArgs args) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\SuccessStory.cs:line 0

**Comment by Lacro59** [comment]
duplicate: #235
