### ISSUE TITLE
Epic achievements not displaying/updating

### ISSUE THREAD

**Issue by drnooooo** [Lacro59/playnite-successstory-plugin#299]
I've been unable to get Epic achievements to update or display. Before I was using manual achievements for games like Bugsnax, but now that Bugsnax has official achievements, updating or downloading them doesn't display them. It's the same for Hades, which worked in the past.

Extensions log says this. I am authenticated according to the Epic Games library addon.

```
20-05 15:22:45.895|WARN |SuccessStory#GenericAchievements:Epic user is not authenticated
20-05 15:22:45.895|INFO |SuccessStory#PluginDatabaseObject`4:Task Refresh() - 00:00.09 for 0/4 items
20-05 15:22:50.528|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Bugsnax - 51b521ad-f8f2-4e5a-8003-89821063a9ac)
20-05 15:22:50.548|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Bugsnax - 51b521ad-f8f2-4e5a-8003-89821063a9ac
20-05 15:23:26.717|ERROR|EpicLibrary#EpicAccountClient:Failed to load saved tokens.
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamReader.Dispose(Boolean disposing)
   at System.IO.TextReader.Dispose()
   at PlayniteExtensions.Common.Encryption.DecryptFromFile(String inputFile, Encoding encoding, String password) in E:\Devel\PlayniteExtensions\source\Generic\PlayniteExtensions.Common\Encryption.cs:line 86
   at EpicLibrary.Services.EpicAccountClient.loadTokens() in E:\Devel\PlayniteExtensions\source\Libraries\EpicLibrary\Services\EpicAccountClient.cs:line 307
20-05 15:25:21.499|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Bugsnax - 51b521ad-f8f2-4e5a-8003-89821063a9ac)
20-05 15:25:21.740|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.EpicAchievements for Bugsnax - 51b521ad-f8f2-4e5a-8003-89821063a9ac
20-05 15:25:22.124|ERROR|SuccessStory#Common:Failed to load saved cookies|D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs|172
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamReader.Dispose(Boolean disposing)
   at System.IO.TextReader.Dispose()
   at CommonPlayniteShared.Common.Encryption.DecryptFromFile(String inputFile, Encoding encoding, String password) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPlayniteShared\Common\Encryption.cs:line 86
   at CommonPluginsStores.StoreApi.GetStoredCookies() in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 172
20-05 15:25:22.124|INFO |SuccessStory#StoreApi:No stored cookies
20-05 15:25:23.294|WARN |SuccessStory#StoreApi:Error 404 for Bugsnax
20-05 15:25:23.294|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Bugsnax - 51b521ad-f8f2-4e5a-8003-89821063a9ac
20-05 15:28:12.311|ERROR|UplayLibrary#UplayMetadataProvider:Failed to get Uplay product info from cache.
```

**Comment by psychopattt** [comment]
I have a similar problem. I can't obtain achievements from any Epic Store games, including games which were working in the past.

```
31-05 17:30:18.662|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(while True: learn() - 6102b068-ff19-4a64-992a-6f23c146ac4b)
31-05 17:30:19.156|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.EpicAchievements for while True: learn() - 6102b068-ff19-4a64-992a-6f23c146ac4b
31-05 17:30:20.362|WARN |SuccessStory#StoreApi:Error 404 for while True: learn()
31-05 17:30:20.362|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for while True: learn() - 6102b068-ff19-4a64-992a-6f23c146ac4b
31-05 17:33:47.739|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Black Widow: Recharged - a7c18576-fffb-4c4a-9920-4a2e088bcc92)
31-05 17:33:47.739|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.EpicAchievements for Black Widow: Recharged - a7c18576-fffb-4c4a-9920-4a2e088bcc92
31-05 17:33:48.961|WARN |SuccessStory#StoreApi:Error 404 for Black Widow: Recharged
31-05 17:33:48.961|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Black Widow: Recharged - a7c18576-fffb-4c4a-9920-4a2e088bcc92
```

**Comment by Jhanlon95** [comment]
@Lacro59 I done some debugging on this as I am also experiencing this issue and I believe there is some kind of browser check being done when trying to get the achievements. When looking at the response when trying to download the achievement data I am seeing this

![image](https://user-images.githubusercontent.com/11045596/173206720-efb7d674-59a7-485c-ab23-3dfdc5d215c9.png)

There is more to indicate that their is some kind of challange screen being encountered. I've attached the HTML that's being returned

[epicChallenge.txt](https://github.com/Lacro59/playnite-successstory-plugin/files/8884832/epicChallenge.txt)
