### ISSUE TITLE
Extension failed to load

### ISSUE THREAD

**Issue by pedro2d10** [Lacro59/playnite-successstory-plugin#354]
Hello, 

I have a issue with this extension. At startup it failed to load. 
My playnite version is 10.3 and I tried with the latest version of this plugin.

Here the errors I founds:
`
17-01 11:12:00.508|ERROR|ExtensionFactory:Failed to load plugin: SuccessStory
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: X. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Playnite.Common.Serialization.FromJsonStream[T](Stream stream) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 340
   at Playnite.Common.Serialization.FromJsonFile[T](String filePath) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 391
   at Playnite.Common.DataSerializer.FromJsonFile[T](String filePath) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 90
   at Playnite.SDK.Data.Serialization.FromJsonFile[T](String filePath) in C:\projects\playnite\source\PlayniteSDK\Data\DataSerialization.cs:line 478
   at Playnite.SDK.Plugins.Plugin.LoadPluginSettings[TSettings]() in C:\projects\playnite\source\PlayniteSDK\Plugins\Plugin.cs:line 346
   at SuccessStory.SuccessStorySettingsViewModel..ctor(SuccessStory plugin) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\SuccessStorySettings.cs:line 399
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.ObjectExtensions.CrateInstance[T](Type type, Object[] parameters) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPlayniteShared\Common\Extensions\ObjectExtensions.cs:line 37
   at CommonPluginsShared.PlayniteExtended.PlaynitePlugin`1..ctor(IPlayniteAPI api) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\PlayniteExtended\PluginExtended.cs:line 129
   at CommonPluginsShared.PlayniteExtended.PluginExtended`2..ctor(IPlayniteAPI api) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\PlayniteExtended\PluginExtended.cs:line 28
   at SuccessStory.SuccessStory..ctor(IPlayniteAPI api) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\SuccessStory.cs:line 48
`

Thank's for the help

**Comment by pedro2d10** [comment]
I find out how to resolve my own issue. If it can help someone, here what I did:

1. Remove the plugin
2. Go to extension data folder `%appdata%\Playnite\ExtensionsData`
3. find the folder containind a successstory folder and delete it
4. Restart playnite and reinstal the extension
