### ISSUE TITLE
Achievements are empty, plugin start error?

### ISSUE THREAD

**Issue by duartenina** [Lacro59/playnite-successstory-plugin#360]
Hi,

While Playnite does not warn of any issue with SuccessStory, the achievement screen is empty with 0 games. The log does show an error:

```ExtensionFactory:Failed to execute OnApplicationStarted method from SuccessStory plugin.
System.NullReferenceException: Object reference not set to an instance of an object.
   at CommonPluginsShared.Models.TraceInfos..ctor(Exception ex) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\Models\TraceInfos.cs:line 25
   at CommonPluginsShared.Common.LogError(Exception ex, Boolean IsIgnored, String Message, Boolean ShowNotification, String PluginName, String NotificationMessage) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\Common.cs:line 222
   at SuccessStory.Clients.RetroAchievements.GetConsoleIDs() in D:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs:line 204
   at SuccessStory.SuccessStory.OnApplicationStarted(OnApplicationStartedEventArgs args) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\SuccessStory.cs:line 1075
   at Playnite.Plugins.ExtensionFactory.NotifiyOnApplicationStarted() in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 727
```

I'm running Playnite 10.9 and SuccessStory is version 3.1.

[playnite_clean.log](https://github.com/Lacro59/playnite-successstory-plugin/files/10824167/playnite_clean.log)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/pull/356
