### ISSUE TITLE
Error updating Tainted Grail on GOG

### ISSUE THREAD

**Issue by JustThat70** [Lacro59/playnite-successstory-plugin#394]
```
22-07 23:43:07.634|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Tainted Grail: Conquest - bdcd31cf-cfb4-4293-95af-1b8fd6fcff44)
22-07 23:43:07.640|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.GogAchievements for Tainted Grail: Conquest - bdcd31cf-cfb4-4293-95af-1b8fd6fcff44
22-07 23:43:08.204|ERROR|SuccessStory#Common:Error on GetJsonInString()|D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\Tools.cs|187
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at CommonPluginsShared.Tools.GetJsonInString(String str, String strStart, String strEnd, String strPurge) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\Tools.cs:line 187
22-07 23:43:09.245|ERROR|SuccessStory#Common:Error on GetJsonInString()|D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\Tools.cs|187
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at CommonPluginsShared.Tools.GetJsonInString(String str, String strStart, String strEnd, String strPurge) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\Tools.cs:line 187
22-07 23:43:09.248|ERROR|SuccessStory#Common:Error on GetAchievements()|D:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\GogAchievements.cs|40
System.NullReferenceException: Object reference not set to an instance of an object.
   at CommonPluginsStores.Gog.GogApi.GetAchievementsSourceLink(String Name, String Id, AccountInfos accountInfos) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Gog\GogApi.cs:line 352
   at SuccessStory.Clients.GogAchievements.GetAchievements(Game game) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\GogAchievements.cs:line 40
22-07 23:43:12.985|INFO |SuccessStory#PluginDatabaseObject`4:Find 40 achievements find for Tainted Grail: Conquest - bdcd31cf-cfb4-4293-95af-1b8fd6fcff44
22-07 23:43:19.473|DEBUG|GogLibrary#Downloader:Downloading string content from https://api.gog.com/products/1257094744?expand=description&locale=en using cookies and System.Text.UTF8Encoding encoding.
22-07 23:43:20.174|DEBUG|GogLibrary#Downloader:Downloading string content from https://www.gog.com/en/game/tainted_grail using cookies and System.Text.UTF8Encoding encoding.
```

**Comment by Lacro59** [comment]
fixed
