### ISSUE TITLE
Value cannot be null Parameter name: source

### ISSUE THREAD

**Issue by LukePeltier** [Lacro59/playnite-successstory-plugin#399]
```
01-08 20:04:16.022|ERROR|SuccessStory#Common:Error on <GetSelectData>b__3()|D:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs|1459
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at SuccessStory.Models.GameAchievements.SetRaretyIndicator() in D:\GitHub\Lacro59\playnite-successstory-plugin\source\Models\GameAchievements.cs:line 365
   at SuccessStory.Clients.XboxAchievements.GetAchievements(Game game) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\XboxAchievements.cs:line 104
   at SuccessStory.Services.SuccessStoryDatabase.GetWeb(Guid Id) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 273
   at SuccessStory.Services.SuccessStoryDatabase.Get(Guid Id, Boolean OnlyCache, Boolean Force) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 215
   at CommonPluginsShared.Collections.PluginDatabaseObject`4.Get(Game game, Boolean OnlyCache, Boolean Force) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\Collections\PluginDatabaseObject.cs:line 630
   at SuccessStory.Services.SuccessStoryDatabase.<>c__DisplayClass41_0.<GetSelectData>b__3(GlobalProgressActionArgs activateGlobalProgress) in D:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 1459
```

Still seeing this issue on 3.1.3

**Comment by ExtinctAnt** [comment]
i have the same issue
