### ISSUE TITLE
Can't find achievements for Steam games

### ISSUE THREAD

**Issue by jnxtrm** [Lacro59/playnite-successstory-plugin#412]
Achievements are not synchronizing on Steam games. extensions.log shows this error:

```
18-11 20:19:11.193|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(ELDEN RING - 0ed7143d-2494-4f06-82e2-866514c8141f)
18-11 20:19:14.249|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for ELDEN RING - 0ed7143d-2494-4f06-82e2-866514c8141f
18-11 20:19:14.249|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, EnableSteamWithoutWebApi: True, SteamIsPrivate: False
18-11 20:17:21.555|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for ELDEN RING - 0ed7143d-2494-4f06-82e2-866514c8141f
```

I use the plugin with Disable API Usage option.

**Comment by psychopattt** [comment]
I'm having the same problem. I'm using a public account and I have the "Disable API usage" option checked.
```
19-11 08:42:54.378|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Battlefield 2042 - 9697bb28-5dbf-4974-8545-8d856d3a6574)
19-11 08:42:54.723|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for Battlefield 2042 - 9697bb28-5dbf-4974-8545-8d856d3a6574
19-11 08:42:54.723|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, EnableSteamWithoutWebApi: True, SteamIsPrivate: False
19-11 08:42:56.427|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Battlefield 2042 - 9697bb28-5dbf-4974-8545-8d856d3a6574
```

**Comment by Cam9731** [comment]
Same for me currently

**Comment by epeternally** [comment]
Same on my end. Errors that the account is private (it isn't) and I don't have an API key (I do). Here's the relevant portion of my log file.

[epeternally successstory log 11-12-23.txt](https://github.com/Lacro59/playnite-successstory-plugin/files/13445071/epeternally.successstory.log.11-12-23.txt)

**Comment by LottAustin** [comment]
Also having this error account is private and I do have  an API key. The Playnite Steam Lib also uses this key and is successfully pulling data so the Key should be good.

```
22-11 20:34:40.970|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(DARK SOULS III - 59b4533b-d911-480b-80f3-386ea4a81fbe)
22-11 20:34:40.970|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for DARK SOULS III - 59b4533b-d911-480b-80f3-386ea4a81fbe
22-11 20:34:40.970|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, EnableSteamWithoutWebApi: False, SteamIsPrivate: True
22-11 20:34:43.074|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for DARK SOULS III - 59b4533b-d911-480b-80f3-386ea4a81fbe
```

**Comment by LilJay86** [comment]
Same Problem here :(

`24-11 20:25:05.233|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for Starfield - 400d0ee8-df4f-4a19-95f1-73142772aac2
24-11 20:25:05.233|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, EnableSteamWithoutWebApi: False, SteamIsPrivate: True
24-11 20:25:09.967|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Starfield - 400d0ee8-df4f-4a19-95f1-73142772aac2`

**Comment by death7lord** [comment]
I have the same problem too. I can't load Steam achievements. Everything is fine with the EA platform.

**Comment by SiTWulf** [comment]
Same problem in here with Steam.
API key in use

**Comment by EazyCheeze1978** [comment]
Chiming in - Having this issue as well - Achievements section in the Details does not even spawn for new games. API key is NOT in use for me. Have not needed it before.

**Comment by death7lord** [comment]
[SparrowBrain](https://github.com/SparrowBrain) How add, edit and compilation it?

**Comment by BrunoYDev** [comment]
Ok basically, the api doesn't work with customized url's

**Comment by SparrowBrain** [comment]
I'm still not sure what's happening. I've managed to sync my achievements by using Steam API key.

For people who use Steam API key I would suggest trying to login in SuccessStory extension again. There might be an issue with old cookies (something changed with the way Steam API is used in SuccessStory).

I have no idea how non-Steam API achievements would work, since the code that retrieves that is commented out.

**Comment by LottAustin** [comment]
Reauthorized, uninstalled, and cleared all plugin data still not working.

I haven't had time to pull and compile it locally to see if that would work, but @SparrowBrain if you know where the cookie you are referring to is stored in the file system I could try manually deleting it to see if that corrects the behaviour.

**Comment by PescheHelfer** [comment]
Also doesn't work for me. I can at least add the achievements by right clicking on the game and then add, but this will only add the possible achievements, not my personal progress with them.

**Comment by SparrowBrain** [comment]
@LottAustin I cannot verify, since I don't have access to my PC, but it should be there: https://www.reddit.com/r/playnite/comments/qp2ey1/success_story_steam_achievments/

I think the file is called `steam.json`

It could also be, that my medling with the code is what made it work for me... I uncommented the web scrapping bit in SteamAcievementa.cs: https://github.com/Lacro59/playnite-successstory-plugin/blob/6ed5d5682d17113a832e333c8426b5f316742e2d/source/Clients/SteamAchievements.cs#L1262

I was also messing around with cookies are supplied to the http client, but if you don't see exceptions for that, I doubt it matters.

**Comment by LottAustin** [comment]
Hmmm ya, seems like manually purging the cached authentication is not saving the day. I will see about setting try to pull the code down later removing the comments and compelling it my self later, to see if that fixes the issue.

**Comment by triadne** [comment]
I'm not getting any achievements from Steam either.
I did have the setting ticked like everyone here, but I tried to follow the instructions to input my steam API key but main menu > Add-ons > Extension settings > Generic > SuccessStory > Library does not exist, there is nowhere for me to input my api key.

**Comment by pmrpla** [comment]
With the latest SuccessStory update and a public Steam profile I now get the achievements imported but none are marked as unlocked and I've tested "refresh data" in several games.

**Comment by PescheHelfer** [comment]
> With the latest SuccessStory update and a public Steam profile I now get the achievements imported but none are marked as unlocked and I've tested "refresh data" in several games.

I got the exact same problem. Also see [#441](https://github.com/Lacro59/playnite-successstory-plugin/issues/441#issue-2069261563)

**Comment by LottAustin** [comment]
So, I there is improvement with the latest version I get achievements but there are still issues. For one not all of them seem to be importing, thought it might be a rate limit or some type of throttling so tried it again for some some games using refresh data and actually lost unlocked achievements. log seems to point there is some improper handling of a null-able value.

Full log for the action:
```
07-01 23:09:19.093|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(STAR OCEAN - THE LAST HOPE - 4K & Full HD Remaster - cb513d37-3476-49b8-9b91-01a9e373f9b1)
07-01 23:09:19.093|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for STAR OCEAN - THE LAST HOPE - 4K & Full HD Remaster - cb513d37-3476-49b8-9b91-01a9e373f9b1
07-01 23:09:19.093|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, HasApiKey: True, SteamIsPrivate: True
07-01 23:09:19.845|INFO |SuccessStory#SteamAchievements:SteamApi.GetAchievements()
07-01 23:09:23.314|INFO |SuccessStory#PluginDatabaseObject`4:Find 46 achievements find for STAR OCEAN - THE LAST HOPE - 4K & Full HD Remaster - cb513d37-3476-49b8-9b91-01a9e373f9b1
07-01 23:15:32.688|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(STAR OCEAN - THE LAST HOPE - 4K & Full HD Remaster - cb513d37-3476-49b8-9b91-01a9e373f9b1)
07-01 23:15:32.688|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for STAR OCEAN - THE LAST HOPE - 4K & Full HD Remaster - cb513d37-3476-49b8-9b91-01a9e373f9b1
07-01 23:15:32.688|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, HasApiKey: True, SteamIsPrivate: True
07-01 23:15:33.011|ERROR|SuccessStory#Common:Error on GetAchievements()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Steam\SteamApi.cs|412
System.NullReferenceException: Object reference not set to an instance of an object.
   at CommonPluginsStores.Steam.SteamApi.GetAchievements(String Id, AccountInfos accountInfos) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Steam\SteamApi.cs:line 412
07-01 23:15:33.011|INFO |SuccessStory#SteamAchievements:Old
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_DEFEAT_0 - Percent: 55.1
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_DEFEAT_1 - Percent: 34.2
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_DEFEAT_2 - Percent: 29.5
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_DEFEAT_3 - Percent: 27.1
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_DEFEAT_4 - Percent: 20.6
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_DEFEAT_6 - Percent: 16
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_TREASURE_50 - Percent: 15.4
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_MONSTER_50 - Percent: 14.7
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_DEFEAT_7 - Percent: 14.5
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_DEFEAT_8 - Percent: 11.6
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_PRIVATEED_07 - Percent: 8.6
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_PRIVATEED_01 - Percent: 8.6
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_PRIVATEED_06 - Percent: 8.5
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_PRIVATEED_04 - Percent: 8.3
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_ARTS_15 - Percent: 7.9
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_PRIVATEED_08 - Percent: 6.5
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_PRIVATEED_03 - Percent: 6.3
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_ARENA_30 - Percent: 5.4
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_QUEST_50 - Percent: 4.2
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_PRIVATEED_05 - Percent: 4
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_IC_20 - Percent: 3.9
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_ARENA_10 - Percent: 3.7
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_DEFEAT_9 - Percent: 3.2
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_ARENA_ALL - Percent: 2.8
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_PRIVATEED_02 - Percent: 2.8
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_PRIVATEED_09 - Percent: 2.3
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_ARTS_30 - Percent: 2
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_IC_40 - Percent: 1.6
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_DEFEAT_10 - Percent: 1.4
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_COLLECTION_SPACESHIP_ALL - Percent: 1.4
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_ARTS_45 - Percent: 1.2
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_GAMELELEVEL_0 - Percent: 1
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_IC_60 - Percent: 1
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_MONSTER_ALL - Percent: 1
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_TREASURE_ALL - Percent: 0.8
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_IC_80 - Percent: 0.8
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_ARTS_60 - Percent: 0.8
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_GAMELEVEL_1 - Percent: 0.7
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_QUEST_ALL - Percent: 0.7
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_ARTS_75 - Percent: 0.7
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_BUNNY_100 - Percent: 0.6
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_BUNNY_50 - Percent: 0.6
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_COLLECTION_WEAPON_ALL - Percent: 0.6
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_ARTS_ALL - Percent: 0.6
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_ARTS_90 - Percent: 0.6
07-01 23:15:34.876|WARN |SuccessStory#SteamAchievements:not find for 609150 - ApiName: TROPHY_E_IC_ALL - Percent: 0.5
07-01 23:15:38.178|INFO |SuccessStory#PluginDatabaseObject`4:Find 36 achievements find for STAR OCEAN - THE LAST HOPE - 4K & Full HD Remaster - cb513d37-3476-49b8-9b91-01a9e373f9b1
07-01 23:15:40.250|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\fe184a097d7e99792b2a2e6f038400ff.jpg to E:\Applications\Playnite\cache\SuccessStory\fe184a097d7e99792b2a2e6f038400ff.jpg
07-01 23:15:40.289|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\935a50351b347a87550fe462cc995ea9.jpg to E:\Applications\Playnite\cache\SuccessStory\935a50351b347a87550fe462cc995ea9.jpg
07-01 23:15:40.315|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\d7c2e3c31227815b942de4ee61927220.jpg to E:\Applications\Playnite\cache\SuccessStory\d7c2e3c31227815b942de4ee61927220.jpg
07-01 23:15:40.360|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\bdfc34da29459d3e9293eca5ef366a52.jpg to E:\Applications\Playnite\cache\SuccessStory\bdfc34da29459d3e9293eca5ef366a52.jpg
07-01 23:15:40.386|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\fd0c9c222952d6538277312d4cc1cad6.jpg to E:\Applications\Playnite\cache\SuccessStory\fd0c9c222952d6538277312d4cc1cad6.jpg
07-01 23:15:40.422|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\444ace584fce4bd6e368a45ac85f4cfe.jpg to E:\Applications\Playnite\cache\SuccessStory\444ace584fce4bd6e368a45ac85f4cfe.jpg
07-01 23:15:40.478|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\6b3df9262b7a37dbd8dd4d162e14bdaf.jpg to E:\Applications\Playnite\cache\SuccessStory\6b3df9262b7a37dbd8dd4d162e14bdaf.jpg
07-01 23:15:40.505|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\879a3186314f7197fb7a3bd98dfbdfc5.jpg to E:\Applications\Playnite\cache\SuccessStory\879a3186314f7197fb7a3bd98dfbdfc5.jpg
07-01 23:15:40.531|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\9fe9d18476f80de10ac08ec2f164f950.jpg to E:\Applications\Playnite\cache\SuccessStory\9fe9d18476f80de10ac08ec2f164f950.jpg
07-01 23:15:40.556|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\0d04274497374c3f4797fac497ab8cf0.jpg to E:\Applications\Playnite\cache\SuccessStory\0d04274497374c3f4797fac497ab8cf0.jpg
07-01 23:15:40.587|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\f0c0fcf6fd180bee419af4bcd79a1eeb.jpg to E:\Applications\Playnite\cache\SuccessStory\f0c0fcf6fd180bee419af4bcd79a1eeb.jpg
07-01 23:15:40.612|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\6930f42fda5b6801bb13942448be5abd.jpg to E:\Applications\Playnite\cache\SuccessStory\6930f42fda5b6801bb13942448be5abd.jpg
07-01 23:15:40.637|DEBUG|SuccessStory#FileSystem:Copying file E:\Applications\Playnite\cache\images\3994a93eed73752dc4d85571764386c6.jpg to E:\Applications\Playnite\cache\SuccessStory\3994a93eed73752dc4d85571764386c6.jpg
07-01 23:16:04.125|ERROR|SuccessStory#Common:Error on GetCountByDay()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs|751
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at SuccessStory.Services.SuccessStoryDatabase.<>c.<GetCountByDay>b__25_5(Achievements x, Achievements y) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 751
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at SuccessStory.Services.SuccessStoryDatabase.GetCountByDay(Nullable`1 GameID, Int32 limit, Boolean CutPeriod) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 751
07-01 23:16:04.231|ERROR|SuccessStory#Common:Error on GetCountByDay()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs|751
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at SuccessStory.Services.SuccessStoryDatabase.<>c.<GetCountByDay>b__25_5(Achievements x, Achievements y) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 751
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at SuccessStory.Services.SuccessStoryDatabase.GetCountByDay(Nullable`1 GameID, Int32 limit, Boolean CutPeriod) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 751
07-01 23:16:54.119|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(STAR OCEAN - THE LAST HOPE - 4K & Full HD Remaster - cb513d37-3476-49b8-9b91-01a9e373f9b1)
07-01 23:16:54.119|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for STAR OCEAN - THE LAST HOPE - 4K & Full HD Remaster - cb513d37-3476-49b8-9b91-01a9e373f9b1
07-01 23:16:54.119|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, HasApiKey: True, SteamIsPrivate: True
07-01 23:16:54.231|ERROR|SuccessStory#Common:Error on GetAchievements()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Steam\SteamApi.cs|412
System.NullReferenceException: Object reference not set to an instance of an object.
   at CommonPluginsStores.Steam.SteamApi.GetAchievements(String Id, AccountInfos accountInfos) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Steam\SteamApi.cs:line 412
```
