### ISSUE TITLE
[BUG] Error when getting/refreshing achievement data

### ISSUE THREAD

**Issue by BloodShed-Oni** [Lacro59/playnite-successstory-plugin#419]
When getting/refreshing achievement data for one or multiple games for following error pops up

```
SuccessStory
Input string '1.0 is not a valid
integer. Path 'games.pages', line
1, position 90.
```
Data still gets downloaded from what I can tell.

Extensions.log
```
06-12 17:39:34.883|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Turok 3: Shadow of Oblivion - 947c2a55-8de3-48f0-9d27-e68383ad5120)
06-12 17:39:34.883|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for Turok 3: Shadow of Oblivion - 947c2a55-8de3-48f0-9d27-e68383ad5120
06-12 17:39:34.884|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, EnableSteamWithoutWebApi: False, SteamIsPrivate: False
06-12 17:39:35.690|INFO |SuccessStory#SteamAchievements:No Steam stats for 1996770
06-12 17:39:38.407|ERROR|SuccessStory#Common:Error on SearchGame()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\ExophaseAchievements.cs|227
Newtonsoft.Json.JsonReaderException: Input string '1.0' is not a valid integer. Path 'games.pages', line 1, position 90.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Common.Serialization.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 336
   at Playnite.Common.DataSerializer.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 80
   at Playnite.SDK.Data.Serialization.FromJson[T](String json) in C:\projects\playnite\source\PlayniteSDK\Data\DataSerialization.cs:line 406
   at SuccessStory.Clients.ExophaseAchievements.SearchGame(String Name) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\ExophaseAchievements.cs:line 227
06-12 17:39:38.407|WARN |SuccessStory#ExophaseAchievements:No game found for Turok 3: Shadow of Oblivion in GetAchievementsPageUrl()
06-12 17:39:38.470|ERROR|SuccessStory#Common:Error on SearchGame()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\ExophaseAchievements.cs|227
Newtonsoft.Json.JsonReaderException: Input string '1.0' is not a valid integer. Path 'games.pages', line 1, position 90.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Common.Serialization.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 336
   at Playnite.Common.DataSerializer.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 80
   at Playnite.SDK.Data.Serialization.FromJson[T](String json) in C:\projects\playnite\source\PlayniteSDK\Data\DataSerialization.cs:line 406
   at SuccessStory.Clients.ExophaseAchievements.SearchGame(String Name) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\ExophaseAchievements.cs:line 227
06-12 17:39:38.470|WARN |SuccessStory#ExophaseAchievements:No game found for turok 3 shadow of oblivion in GetAchievementsPageUrl()
06-12 17:39:38.537|ERROR|SuccessStory#Common:Error on SearchGame()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\ExophaseAchievements.cs|227
Newtonsoft.Json.JsonReaderException: Input string '1.0' is not a valid integer. Path 'games.pages', line 1, position 90.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Common.Serialization.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 336
   at Playnite.Common.DataSerializer.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 80
   at Playnite.SDK.Data.Serialization.FromJson[T](String json) in C:\projects\playnite\source\PlayniteSDK\Data\DataSerialization.cs:line 406
   at SuccessStory.Clients.ExophaseAchievements.SearchGame(String Name) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\ExophaseAchievements.cs:line 227
06-12 17:39:38.539|WARN |SuccessStory#ExophaseAchievements:No game found for Turok 3 in GetAchievementsPageUrl()
06-12 17:39:38.539|WARN |SuccessStory#ExophaseAchievements:No Exophase (description) url find for Turok 3: Shadow of Oblivion - 947c2a55-8de3-48f0-9d27-e68383ad5120
06-12 17:39:40.267|INFO |SuccessStory#PluginDatabaseObject`4:Find 35 achievements find for Turok 3: Shadow of Oblivion - 947c2a55-8de3-48f0-9d27-e68383ad5120

```

**Comment by LeMimit** [comment]
Hello ! Got the same error on my side since yesterday evening.

**Comment by Stuke00** [comment]
Same error fo rme

**Comment by Vildiil** [comment]
Same error for me as well

**Comment by Thexder0** [comment]
Same. It seems just cosmetic at this point, let us know if we can provide info to help debugging this,

**Comment by LordBoos** [comment]
Same.

**Comment by ScrewThisNoise** [comment]
Also seem to experience this, does seem very random which games it happens to though, thought first it was games with japanese letters, but seem to randomly happen to other games as well, and then suddenly work when retrying

**Comment by Xeero13** [comment]
same for me, but this happened after i manually input my steam API. initially the error is no account authenticated which is false because my account is authenticated. The issue is, no data is being updated so I tried manually putting the API. This fixed the data issue, now my new achievements are seen but I get this same Input string error message.

**Comment by LeMimit** [comment]
it seems with this error I have no way to update the progress of my successes.
I would like to help solving this error but sadly I have no clues on how to develop playnite plugin :(

**Comment by Kayzels** [comment]
This issue is the same one I encountered. It's got to do with the way it serialises data from Exophase. Changing one line in the code solved it for me, so I made a pull request for it: #418 

Other issues are reporting the same thing: #417, #421

You can fix it for yourself, but you'll need to setup a Playnite plugin dev environment, and install all the dependencies using Nuget, and then build the plugin.

**Comment by Lacro59** [comment]
duplicate #417
