### ISSUE TITLE
Input string '1.0' is not a valid integer. Path 'games.pages', line 1, position 90.

### ISSUE THREAD

**Issue by Kinc4id** [Lacro59/playnite-successstory-plugin#421]
I get the above error message every time when Playnite launches.

**Comment by trillex** [comment]
I get the same, here is a bit of log: 

`09-12 22:40:30.778|DEBUG|GamesEditor:Using plugin to start a game.
09-12 22:41:54.940|INFO |GamesEditor:Starting Baldur's Gate 3, 7d0869dc-6570-432c-a727-86dc5ed84094, 1086940, cb91dfc9-b977-43bf-8e70-55f46e410fab
09-12 22:41:54.953|DEBUG|GamesEditor:Using plugin to start a game.
09-12 22:42:02.986|ERROR|Serialization:Failed to deserialize SuccessStory.Models.ExophaseSearchResult from json:
Newtonsoft.Json.JsonReaderException: Input string '1.0' is not a valid integer. Path 'games.pages', line 1, position 90.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Common.Serialization.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 330
09-12 22:42:03.067|DEBUG|Serialization:{"success":true,"games":{"collection":[],"found":4,"sort":"added","filters":[],"pages":1.0,"list":[{"master_id":637401,"total_exp":13483,"global_players":210,"global_complete":0,"total_awards":54,"total_points":1000,"title":"Baldur's Gate 3","environment_slug":"xbox","platforms":[{"termTaxonomyId":99489,"termId":105626,"name":"Xbox Series","slug":"xbox-series"}],"regions":null,"endpoint_awards":"https:\/\/www.exophase.com\/game\/baldur-s-gate-3-xbox\/achievements\/","images":{"l":"https:\/\/m.exophase.com\/xbox\/games\/l\/6d83de1.png?374a451728a63164e43a386e2cc383cb","m":"https:\/\/m.exophase.com\/xbox\/games\/m\/6d83de1.png?374a451728a63164e43a386e2cc383cb","s":"https:\/\/m.exophase.com\/xbox\/games\/s\/6d83de1.png?374a451728a63164e43a386e2cc383cb"}},{"master_id":616495,"total_exp":19901,"global_players":15943,"global_complete":32,"total_awards":55,"total_points":1395,"title":"Baldur's Gate 3","environment_slug":"psn","platforms":[{"termTaxonomyId":9,"termId":9,"name":"PS5","slug":"ps5"}],"regions":null,"endpoint_awards":"https:\/\/www.exophase.com\/game\/baldur-s-gate-3-psn\/trophies\/","images":{"l":"https:\/\/m.exophase.com\/psn\/games\/l\/dg5dde3.png?6d1c3f5c93fe4b4f5c41bb623f5fef18","m":"https:\/\/m.exophase.com\/psn\/games\/m\/dg5dde3.png?6d1c3f5c93fe4b4f5c41bb623f5fef18","s":"https:\/\/m.exophase.com\/psn\/games\/s\/dg5dde3.png?6d1c3f5c93fe4b4f5c41bb623f5fef18"}},{"master_id":344474,"total_exp":36845,"global_players":72052,"global_complete":32,"total_awards":54,"total_points":0,"title":"Baldur's Gate 3","environment_slug":"steam","platforms":[{"termTaxonomyId":12,"termId":12,"name":"Steam","slug":"steam"}],"regions":null,"endpoint_awards":"https:\/\/www.exophase.com\/game\/baldur-s-gate-3-steam\/achievements\/","images":{"l":"https:\/\/m.exophase.com\/steam\/games\/l\/50edge.png?a0ee9cf765b1df5cb91fbbdd6b54b77b","m":"https:\/\/m.exophase.com\/steam\/games\/m\/50edge.png?a0ee9cf765b1df5cb91fbbdd6b54b77b","s":"https:\/\/m.exophase.com\/steam\/games\/s\/50edge.png?a0ee9cf765b1df5cb91fbbdd6b54b77b"}},{"master_id":191547,"total_exp":9896,"global_players":118,"global_complete":1,"total_awards":54,"total_points":0,"title":"Baldur's Gate 3","environment_slug":"gog","platforms":[{"termTaxonomyId":2,"termId":2,"name":"GOG","slug":"gog"}],"regions":null,"endpoint_awards":"https:\/\/www.exophase.com\/game\/baldur-s-gate-3-gog\/achievements\/","images":{"l":"https:\/\/m.exophase.com\/gog\/games\/l\/7g80dd.png?1c293a45eab0af520738003e4933b228","m":"https:\/\/m.exophase.com\/gog\/games\/m\/7g80dd.png?1c293a45eab0af520738003e4933b228","s":"https:\/\/m.exophase.com\/gog\/games\/s\/7g80dd.png?1c293a45eab0af520738003e4933b228"}}],"paging":{"current":1,"next":1,"last":1,"total":4}}}
09-12 22:42:05.096|ERROR|Serialization:Failed to deserialize SuccessStory.Models.ExophaseSearchResult from json:
Newtonsoft.Json.JsonReaderException: Input string '1.0' is not a valid integer. Path 'games.pages', line 1, position 90.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Common.Serialization.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 330
`

**Comment by xii7** [comment]
I've been getting this for over a month now.
[SuccessStory_2023-12-11.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/13630707/SuccessStory_2023-12-11.zip)

**Comment by Xeero13** [comment]
same for me
