### ISSUE TITLE
Unable to get trophies for Playstation

### ISSUE THREAD

**Issue by KiimaRo** [Lacro59/playnite-successstory-plugin#431]
[SuccessStory_2023-12-25.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/13766605/SuccessStory_2023-12-25.zip)
Getting a 401 error when trying to get the trophies for my Playstation games, doesn't matter if it's PS3, PS4 or PS5. Sometimes it throws that I am not authenticated, which I am and then goes back to throwing 401 errors straight after.

**Comment by nxllxvxid** [comment]
#https://github.com/Lacro59/playnite-successstory-plugin/issues/425#issuecomment-1866438571

**Comment by BloodShed-Oni** [comment]
> [#425 (comment)](https://github.com/Lacro59/playnite-successstory-plugin/issues/425#issuecomment-1866438571)
> 
> I covered the solution here, it need to be manually triggered after certain actions

OP is talking about PSN achievements, not Retro Achievements.

I'm have the same problem

![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/10365453/dc3b3544-6afa-4e72-a8c5-c4e3a58df25c)

```
02-01 20:45:49.553|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Crash Team Racing Nitro-Fueled - 904fbb7e-a6ee-426e-8ab9-6972ecd1ecbd)
02-01 20:45:50.490|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.PSNAchievements for Crash Team Racing Nitro-Fueled - 904fbb7e-a6ee-426e-8ab9-6972ecd1ecbd
02-01 20:45:51.649|ERROR|SuccessStory#Common:Error on GetAchievements()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\PSNAchievements.cs|98
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommonPluginsShared.Web.<DownloadStringData>d__14.MoveNext() in G:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\Web.cs:line 635
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at SuccessStory.Clients.PSNAchievements.GetAchievements(Game game) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\PSNAchievements.cs:line 98
02-01 20:45:52.215|WARN |SuccessStory#PSNAchievements:No trophiesDetails find for Crash Team Racing Nitro-Fueled - CUSA14876_00
02-01 20:45:52.215|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Crash Team Racing Nitro-Fueled - 904fbb7e-a6ee-426e-8ab9-6972ecd1ecbd

```
