### ISSUE TITLE
Value cannot be null

### ISSUE THREAD

**Issue by Whitechapel-1888** [Lacro59/playnite-successstory-plugin#443]
Success Story version: 3.1.7

When doing downloading plugin data there's this error appearing after completion:
`08-01 10:14:10.142|ERROR|SuccessStory#Common:Error on <GetSelectData>b__3()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs|1465
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at SuccessStory.Clients.RetroAchievements.GetGameIdByHash(Game game, RA_Consoles ra_Consoles) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs:line 440
   at SuccessStory.Clients.RetroAchievements.GetAchievements(Game game) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs:line 81
   at SuccessStory.Services.SuccessStoryDatabase.GetWeb(Guid Id) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 273
   at SuccessStory.Services.SuccessStoryDatabase.Get(Guid Id, Boolean OnlyCache, Boolean Force) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 215
   at CommonPluginsShared.Collections.PluginDatabaseObject`4.Get(Game game, Boolean OnlyCache, Boolean Force) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\Collections\PluginDatabaseObject.cs:line 630
   at SuccessStory.Services.SuccessStoryDatabase.<>c__DisplayClass41_0.<GetSelectData>b__3(GlobalProgressActionArgs activateGlobalProgress) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 1465
`

[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/13858186/extensions.log)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/issues/449
