### ISSUE TITLE
SuccessStory working CPU constantly and other errors

### ISSUE THREAD

**Issue by LukeMW** [Lacro59/playnite-successstory-plugin#495]
This started happening after the latest update.  I detailed everything here: https://new.reddit.com/r/playnite/comments/1eqk3jy/successstory_updated_big_problems/

If you need more info, just ask and I'll be happy to provide it.

**Comment by BloodShed-Oni** [comment]
I have some similar problems and some that I think are related (all started after the 3.2 update).

- I have the blank setting under Steam achievements

- Every time a library update/scan is run this dialog pops up, and takes 190min to complete (I assume it's because of my large library)
![image](https://github.com/user-attachments/assets/46b2f134-8da1-4376-8cd0-ece67f31d62b)

- This error also pops up during the same update/scan
![image](https://github.com/user-attachments/assets/c448e873-1d65-453c-974b-793f70d6b59f)

From extenstions.log
```
13-08 15:33:25.527|INFO |SuccessStory#SuccessStoryDatabase:RefreshNoLoader(Ape Escape: On the Loose - 134554db-8fe6-498b-9961-804c9556ede8 - )
13-08 15:33:25.527|INFO |SuccessStory#SuccessStoryDatabase:Used SuccessStory.Clients.RetroAchievements for Ape Escape: On the Loose - RetroAchievements -  - Sony PSP
13-08 15:33:25.891|ERROR|SuccessStory#Common:Error on GetHash()|C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs|585
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SuccessStory.Clients.RetroAchievements.GetHash(String FilePath, RaPlatformType platformType) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs:line 585
13-08 15:33:25.891|WARN |SuccessStory#RetroAchievements:No game find for Ape Escape: On the Loose with  in PlatformType.All
13-08 15:33:26.131|ERROR|SuccessStory#Common:Error on GetHash()|C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs|585
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SuccessStory.Clients.RetroAchievements.GetHash(String FilePath, RaPlatformType platformType) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs:line 585
13-08 15:33:26.131|WARN |SuccessStory#RetroAchievements:No game find for Ape Escape: On the Loose with  in PlatformType.SNES
13-08 15:33:26.361|ERROR|SuccessStory#Common:Error on GetHash()|C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs|585
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SuccessStory.Clients.RetroAchievements.GetHash(String FilePath, RaPlatformType platformType) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs:line 585
13-08 15:33:26.389|WARN |SuccessStory#RetroAchievements:No game find for Ape Escape: On the Loose with  in PlatformType.SNES
13-08 15:33:26.635|ERROR|SuccessStory#Common:Error on GetHash()|C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs|585
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SuccessStory.Clients.RetroAchievements.GetHash(String FilePath, RaPlatformType platformType) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs:line 585
13-08 15:33:26.635|WARN |SuccessStory#RetroAchievements:No game find for Ape Escape: On the Loose with  in PlatformType.Sega_CD_Saturn
13-08 15:33:26.863|ERROR|SuccessStory#Common:Error on GetHash()|C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs|585
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SuccessStory.Clients.RetroAchievements.GetHash(String FilePath, RaPlatformType platformType) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs:line 585
13-08 15:33:26.863|WARN |SuccessStory#RetroAchievements:No game find for Ape Escape: On the Loose with  in PlatformType.SNES
13-08 15:33:27.091|ERROR|SuccessStory#Common:Error on GetHash()|C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs|585
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SuccessStory.Clients.RetroAchievements.GetHash(String FilePath, RaPlatformType platformType) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs:line 585
```

**Comment by Jhanlon95** [comment]
Disabling "Automatically import for installed games" will stop this from happening. If there's a pop up blocking it's technically a separate window in Playnite and you can close it and it'll go away allowing you make the change I mentioned in the settings at least until this is fixed
