### ISSUE TITLE
Playnite crash when authenticating Steam account

### ISSUE THREAD

**Issue by Terrance** [Lacro59/playnite-successstory-plugin#568]
#### Describe the bug

After signing in and completing Steam Guard verification, `No stored cookies` is logged by the extension, and Playnite reports an unrecoverable error shortly afterwards.

#### To reproduce

1. Menu > _Add-ons..._
2. _Extensions settings_ > _Generic_ > _SuccessStory_
3. _Libraries_ > _Steam_
4. Check _Is private_, then _Authenticate_
5. Login to Steam in the popup (tried both username/password + authenticator approval, and scanning the QR code)
6. Playnite crashes

#### Screenshots

![Unrecoverable error screen](https://github.com/user-attachments/assets/49057a2a-ec32-49c1-b61c-52bc4af584eb)

#### Extensions log

<details>
<summary>extensions.log</summary>

```
15-12 18:37:11.056|WARN |SuccessStory#ItemCollection`1:Failed to deserialize collection item C:\Users\User\AppData\Roaming\Playnite\ExtensionsData\cebe6d32-8c46-4459-b993-5a5189d60788\SuccessStory\16f26269-8848-4b94-aa16-02810f8ba69f.json
15-12 18:37:24.635|INFO |SuccessStory#SuccessStoryDatabase:LoadDatabase with 9082 items - 00:13.73
15-12 18:48:40.296|WARN |SuccessStory#ItemCollection`1:Failed to deserialize collection item C:\Users\User\AppData\Roaming\Playnite\ExtensionsData\cebe6d32-8c46-4459-b993-5a5189d60788\SuccessStory\16f26269-8848-4b94-aa16-02810f8ba69f.json
15-12 18:49:12.342|INFO |SuccessStory#SuccessStoryDatabase:LoadDatabase with 9082 items - 00:33.73
15-12 20:54:02.440|WARN |SuccessStory#GenericAchievements:Steam is not configured
15-12 20:57:01.521|WARN |SuccessStory#StoreApi:No stored cookies
15-12 20:59:14.330|WARN |SuccessStory#ItemCollection`1:Failed to deserialize collection item C:\Users\User\AppData\Roaming\Playnite\ExtensionsData\cebe6d32-8c46-4459-b993-5a5189d60788\SuccessStory\16f26269-8848-4b94-aa16-02810f8ba69f.json
15-12 21:00:01.988|INFO |SuccessStory#SuccessStoryDatabase:LoadDatabase with 9084 items - 00:52.79
15-12 21:01:22.397|WARN |SuccessStory#StoreApi:No stored cookies
15-12 21:02:23.378|WARN |SuccessStory#StoreApi:Expired cookies
15-12 21:02:56.487|INFO |SuccessStory#PluginDatabaseObject`4:RefreshRecent() started
15-12 21:02:56.487|INFO |SuccessStory#PluginDatabaseObject`4:RefreshRecent found 4 game(s) that need updating
15-12 21:02:56.681|INFO |SuccessStory#<>c__DisplayClass28_0:Task Refresh() - 00:00.17 for 4/4 items
15-12 21:53:32.870|WARN |SuccessStory#GenericAchievements:Steam is not configured
15-12 22:03:44.848|WARN |SuccessStory#StoreApi:No stored cookies
```
</details>

<details>
<summary>playnite.log</summary>

```
15-12 20:57:01.484|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.PluginSettingsWindowFactory: c325c318-68ce-4d74-ada6-1db63817a73a
15-12 20:58:31.501|ERROR|PlayniteApplication:Unhandled exception occured.
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at CommonPluginsStores.StoreApi.<>c__DisplayClass60_0.<GetWebCookies>b__2(String y) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 208
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at CommonPluginsStores.StoreApi.<GetWebCookies>b__60_0(HttpCookie x) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 208
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonPluginsStores.StoreApi.GetWebCookies() in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 207
   at CommonPluginsStores.Steam.SteamApi.<>c__DisplayClass53_0.<<Login>b__0>d.MoveNext() in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Steam\SteamApi.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
15-12 20:58:31.992|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory: 0f4456f7-7169-4682-ae6c-e206ec87f0b5
...
15-12 22:03:37.982|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.SettingsWindowFactory: f5216313-9639-4bf7-a1bc-92e2b395c4d9
15-12 22:03:39.483|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.SettingsWindowFactory: f5216313-9639-4bf7-a1bc-92e2b395c4d9, False
15-12 22:03:40.896|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.AddonsWindowFactory: e6486551-3726-4865-bebf-b002d9c424e1
15-12 22:05:39.721|ERROR|PlayniteApplication:Unhandled exception occured.
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at CommonPluginsStores.StoreApi.<>c__DisplayClass60_0.<GetWebCookies>b__2(String y) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 208
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at CommonPluginsStores.StoreApi.<GetWebCookies>b__60_0(HttpCookie x) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 208
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonPluginsStores.StoreApi.GetWebCookies() in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 207
   at CommonPluginsStores.Steam.SteamApi.<>c__DisplayClass53_0.<<Login>b__0>d.MoveNext() in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Steam\SteamApi.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
15-12 22:05:39.761|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory: 1dfbc3aa-7d1e-431f-944e-d9d4ff6cf3a7
```
</details>

**Comment by Terrance** [comment]
Bah, should've just scrolled recent issues rather than searching -- looks like a dupe of #555.
