### ISSUE TITLE
Private Steam account will not authenticate

### ISSUE THREAD

**Issue by chocolatechipcats** [Lacro59/playnite-successstory-plugin#573]
**Describe the bug**
In 3.4.1, attempting to authenticate a private steam account (with or without API key) fails and reverts to 'requires authentication.' This renders the plugin useless for Steam games.

**To Reproduce**
1. Go to settings and input a private account.
2. Authenticate.
3. After inputting the two-factor code from email, SuccessStory reverts to 'requires authentication.' If 'Has API' is checked and API key is inputted, it gets cleared. 

**Expected behavior**
For it to authenticate.

**Screenshots**
![2024-12-21 12_33_35-Add-ons…](https://github.com/user-attachments/assets/d881b778-0a91-49a2-9e34-69d62dc44cb5)

**Comment by awbooze** [comment]
I also have this issue (and have had other Steam-related issues, including #555 - thanks for working through them).

It looks like the relevant section of extensions.log is:
```
27-12 23:23:28.619|ERROR|SuccessStory#Common:Error on GetWebCookies()|C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs|209
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at CommonPluginsStores.StoreApi.<>c__DisplayClass60_0.<GetWebCookies>b__2(String y) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 210
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at CommonPluginsStores.StoreApi.<GetWebCookies>b__60_0(HttpCookie x) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 210
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonPluginsStores.StoreApi.GetWebCookies() in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 209
27-12 23:23:28.856|ERROR|SuccessStory#Common:Error on TryFromJson()|C:\projects\playnite\source\Playnite\Common\Serialization.cs|456
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path 'rgPrimaryLanguage', line 1, position 833. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Common.Serialization.TryFromJson[T](String json, T& deserialized, Exception& error) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 456
```

**Comment by dieeisenefaust** [comment]
I get the same error:

`19-01 11:41:51.423|ERROR|SuccessStory#Common:Error on TryFromJson()|C:\projects\playnite\source\Playnite\Common\Serialization.cs|456
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path 'rgPrimaryLanguage', line 1, position 824. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Common.Serialization.TryFromJson[T](String json, T& deserialized, Exception& error) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 456`

**Comment by dieeisenefaust** [comment]
Also found this:
ects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs|209
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at CommonPluginsStores.StoreApi.<>c__DisplayClass60_0.<GetWebCookies>b__2(String y) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 210
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at CommonPluginsStores.StoreApi.<GetWebCookies>b__60_0(HttpCookie x) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 210
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonPluginsStores.StoreApi.GetWebCookies() in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 209
