### ISSUE TITLE
Cannot load achievement data if profile is not public

### ISSUE THREAD

**Issue by shakeyourbunny** [Lacro59/playnite-successstory-plugin#65]
Hi,

if your profile is not public and set to friends-only,  SuccessStory is not able to download any achievement data from the user.
````
2020-09-05 09:52:10.0817|DEBUG:Downloading string content from https://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v0001/?appid=324810&key=APIKEY&steamid=STEAMID&l=english using System.Text.UTF8Encoding encoding.
2020-09-05 09:52:10.4167|ERROR:SuccessStory [E:\Lacro59\playnite-successstory-plugin\Clients\SteamAchievements.cs 92] - Failed to load from https://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v0001/?appid=324810&key=APIKEY&steamid=STEAMID&l=english.  


System.Net.WebException: The remote server returned an error: (403) Forbidden.


   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at Playnite.Common.Web.Downloader.DownloadString(String url, Encoding encoding)
   at Playnite.Common.Web.HttpDownloader.DownloadString(String url, Encoding encoding)
   at SuccessStory.Clients.SteamAchievements.GetAchievements(IPlayniteAPI PlayniteApi, Guid Id, String PluginUserDataPath, Boolean isLocal) in E:\Lacro59\playnite-successstory-plugin\Clients\SteamAchievements.cs:line 92
````

I guess providing the APIKEY alone is not enough, if your profile is not public.
Please fix.

**Comment by Lacro59** [comment]
Following the different releases, is the problem still present?
